<?php
// $Id$

/**
 * @file
 * Debugging helpers for gmap.
 */

/**
 * Implementation of hook_block().
 */
function gmap_debug_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      return array(
        'gmap_debug' => array(
          'info' => t('GMap Debug'),
        ),
      );

    case 'view':
      if ($delta = 'gmap_debug') {
        drupal_add_js(drupal_get_path('module', 'gmap_debug') .'/gmap_debug.js', 'module', 'header', FALSE, TRUE, FALSE);
        $output = '';
        $output .= theme('menu_item', l(t('Force size check'), '', array('attributes' => array('id' => 'gmap-debug-forcesizecheck'))), FALSE);
        $output .= theme('menu_item', l(t('Reboot map'), '', array('attributes' => array('id' => 'gmap-debug-reboot'))), FALSE);
        return array(
          'subject' => t('GMap Debug'),
          'content' => theme('menu_tree', $output),
        );
      }

  }
}
